// `bob init` — bootstrap a new Bob-shaped agent on disk.
//
// PR-2 lands the directory + file generation. Flair pair (Ed25519 key
// + Agent record) is PR-3; mail consumer is PR-4; Discord+cron are PR-5+.
//
// Layout written:
//   ~/agents/<name>/
//     ├── bob.yaml         # canonical config
//     ├── soul.md             # role's seed soul (caller-editable)
//     ├── bin/<name>          # generated launcher
//     ├── work/               # working dir (empty)
//     ├── memory/             # local memory cache (empty)
//     └── .pi-agent/          # pi-coding-agent state (empty; populated on first run)

import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { type FlairPairResult, flairPair } from "./flair-pair.js";
import type { BobRole } from "./index.js";
import { loadRole } from "./role-loader.js";

// Same character class loadRole uses — agent names are filesystem paths,
// keep them strict-safe.
const AGENT_NAME = /^[a-z0-9-]+$/;

export interface InitOptions {
  name: string;
  role: BobRole;
  provider: string;
  model: string;
  // Where the agent lives. Defaults to ~/agents/<name>/. Tests override.
  agentsRoot?: string;
  // Used for the launcher's PATH hint. Defaults to the Bun runtime we expect.
  bunPath?: string;
  // If true, refuse to overwrite an existing agent dir. Defaults to true.
  noClobber?: boolean;
  // Where Ed25519 keys live. Defaults to ~/.flair/keys/. Tests override.
  // When undefined AND skipFlair is false, defaults apply.
  flairKeysDir?: string;
  // If true, skip Ed25519 keypair generation entirely. For dry-runs or
  // hostless tests that don't want the .flair dir polluted.
  skipFlair?: boolean;
}

export interface InitResult {
  agentDir: string;
  files: string[];
  // Populated unless skipFlair=true. Registration with Flair is a
  // separate step (registerWithFlair) — initAgent only generates the
  // keypair on disk to keep the function sync + filesystem-only.
  flair?: FlairPairResult;
}

export function initAgent(opts: InitOptions): InitResult {
  if (!AGENT_NAME.test(opts.name)) {
    throw new Error(`invalid agent name: ${opts.name} (must match ${AGENT_NAME})`);
  }
  // Validates the role + loads the template. Throws on unknown / unsafe role.
  const template = loadRole(opts.role);
  const root = opts.agentsRoot ?? join(homedir(), "agents");
  const agentDir = join(root, opts.name);
  const noClobber = opts.noClobber !== false;

  if (existsSync(agentDir) && noClobber) {
    throw new Error(`agent dir already exists: ${agentDir} (pass --force to overwrite)`);
  }

  const written: string[] = [];

  // Top-level + subdirs
  mkdirSync(join(agentDir, "bin"), { recursive: true });
  mkdirSync(join(agentDir, "work"), { recursive: true });
  mkdirSync(join(agentDir, "memory"), { recursive: true });
  mkdirSync(join(agentDir, ".pi-agent"), { recursive: true });

  // soul.md (from role template; user editable)
  const soulPath = join(agentDir, "soul.md");
  writeFileSync(soulPath, template.soul);
  written.push(soulPath);

  // bob.yaml — canonical config
  const yamlPath = join(agentDir, "bob.yaml");
  writeFileSync(yamlPath, renderBobYaml(opts, template.tools.allow));
  written.push(yamlPath);

  // .pi-agent/{models.json,auth.json} — required for pi 0.75+ to find
  // credentials AND resolve the model when PI_CODING_AGENT_DIR is set
  // (launcher exports it). Written for every provider — see
  // writePiAgentConfig's doc comment for why bare baseUrl configs aren't
  // enough for `bob run`.
  written.push(...writePiAgentConfig(opts, agentDir));

  // bin/<name> launcher
  const binPath = join(agentDir, "bin", opts.name);
  writeFileSync(binPath, renderLauncher(opts));
  chmodSync(binPath, 0o755);
  written.push(binPath);

  // Flair Ed25519 keypair (registration is a separate async step;
  // we only generate the keys on disk here to keep initAgent sync).
  let flair: FlairPairResult | undefined;
  if (!opts.skipFlair) {
    flair = flairPair({
      name: opts.name,
      keysDir: opts.flairKeysDir,
      // No flairUrl — caller invokes registerWithFlair() separately
      // with the URL of their hub.
    });
    written.push(flair.privateKeyPath, flair.publicKeyPath);
  }

  return { agentDir, files: written, flair };
}

function renderBobYaml(opts: InitOptions, toolsAllow: string[]): string {
  // Hand-rolled to avoid pulling in a yaml dependency for the surface PR.
  // PR-3 (Flair pair) will swap in a real yaml emitter.
  const tools = toolsAllow.map((t) => `    - ${t}`).join("\n");
  return `# Bob config — generated by 'bob init'. Edit freely.
agent:
  id: ${opts.name}
  name: ${capitalize(opts.name)}
  role: ${opts.role}

provider:
  name: ${opts.provider}
  model: ${opts.model}

identity:
  # PR-3 populates these (Ed25519 keypair + Flair Agent record).
  flair_url: http://127.0.0.1:9926
  key_file: ~/.flair/keys/${opts.name}.key
  pub_file: ~/.flair/keys/${opts.name}.pub

channels:
  tps_mail:
    inbox: ~/.tps/mail/${opts.name}

# Add cron entries here:
# cron:
#   - name: morning_briefing
#     schedule: "0 9 * * *"
#     prompt: "Compose Nathan's morning briefing."

tools:
  allow:
${tools}

capabilities:
  - flair

flair:
  url: http://127.0.0.1:9926
  agentId: ${opts.name}
  keyFile: ~/.flair/keys/${opts.name}.key
`;
}

function renderLauncher(opts: InitOptions): string {
  // sh shebang (NOT zsh) — re-sourcing ~/.zshenv on every invocation
  // clobbers env-prefix calls like FOO=bar <agent>. See
  // feedback_shebang_env_prefix in flint's memory.
  const piProvider = resolvePiProvider(opts.provider);
  return `#!/bin/sh
# Generated by 'bob init'. Don't edit — re-run init to update.
# Edit ~/agents/${opts.name}/bob.yaml for config changes.

AGENT_DIR=${homedirEscape()}/agents/${opts.name}
export PI_CODING_AGENT_DIR="$AGENT_DIR/.pi-agent"

# Identity for any git commits the agent makes
export GIT_AUTHOR_NAME="${capitalize(opts.name)}"
export GIT_AUTHOR_EMAIL="${opts.name}@tps.dev"
export GIT_COMMITTER_NAME="${capitalize(opts.name)}"
export GIT_COMMITTER_EMAIL="${opts.name}@tps.dev"

# Optional GitHub PAT for intel-gathering (releases.atom polling, REST API).
# Sourced from a 0600 file so the token never lands in process listings or
# env-dump output. If the file is missing the agent still runs — GitHub
# anonymous calls just get the ~60/hr rate limit instead of 5000/hr.
GH_PAT_FILE="$HOME/.tps/secrets/${opts.name}-github-pat"
if [ -r "$GH_PAT_FILE" ]; then
  GH_TOKEN=$(cat "$GH_PAT_FILE")
  export GH_TOKEN
fi

cd "$AGENT_DIR/work"
# TODO(phase1): migrate to SDK — the persistent/interactive agent runtime
# embeds pi via createAgentSession (mirrors run.ts) and this generated
# launcher goes away. Kept for now; PR1 only migrates run.ts's non-interactive
# prompt path. run.ts already reads provider/model from bob.yaml and appends
# soul.md the same way this launcher does.
# --append-system-prompt loads the role-customized persona from soul.md.
# Without this, pi runs with the default coding-assistant prompt and the
# agent identity is lost. See reference_bob_init_papercuts.
exec pi --provider ${piProvider} --model ${opts.model} \\
  --append-system-prompt "$(cat $AGENT_DIR/soul.md)" "$@"
`;
}

// Translate bob's conceptual provider names into pi's actual provider IDs.
// `exe-dev-gateway` is bob's term for "anthropic API shape, routed through
// the exe.dev VM-authenticated proxy" — pi only knows the underlying
// provider (`anthropic`), and we configure the baseUrl override via
// .pi-agent/models.json (see writePiAgentConfig).
function resolvePiProvider(bobProvider: string): string {
  if (bobProvider === "exe-dev-gateway") return "anthropic";
  return bobProvider;
}

// pi 0.75+ reads its config from $PI_CODING_AGENT_DIR (the per-agent
// dir the launcher exports). Without these two files, the launcher
// fails at first invocation with either "No API key found for <provider>"
// (auth.json missing) or "model not found" from pi-coding-agent's
// ModelRegistry.find(provider, model) — which requires the model to be
// DECLARED under providers.<provider>.models, not just a bare baseUrl.
//
// We ALWAYS write both files for ANY provider, because `bob run` resolves
// models strictly (unlike pi's bare launcher, which tolerates a custom id
// with no declaration). Declaring the model is the core fix here.
//
// - models.json: providers.<piProvider>.models = [{ id: opts.model }] always.
//   baseUrl is added only for providers with a known custom endpoint
//   (see knownProviderBaseUrl) — built-ins like anthropic/openai use pi's
//   default endpoint.
// - auth.json: exe-dev-gateway gets its VM-identity placeholder key (the
//   literal value is never checked — the gateway authenticates via VM
//   identity). Every other provider gets a clearly-labeled placeholder the
//   human must replace with a real key before the agent can run.
function knownProviderBaseUrl(bobProvider: string): string | undefined {
  switch (bobProvider) {
    case "exe-dev-gateway":
      return "http://169.254.169.254/gateway/llm/anthropic";
    case "ollama-cloud":
    case "ollama":
      return "https://ollama.com/v1";
    default:
      return undefined;
  }
}

function writePiAgentConfig(opts: InitOptions, agentDir: string): string[] {
  const piDir = join(agentDir, ".pi-agent");
  // mkdirSync above already created it; defensive recreate in case caller
  // didn't go through the standard path.
  mkdirSync(piDir, { recursive: true });

  const piProvider = resolvePiProvider(opts.provider);
  const isGateway = opts.provider === "exe-dev-gateway";
  const baseUrl = knownProviderBaseUrl(opts.provider);
  const key = isGateway ? "exe-gateway-placeholder" : "REPLACE_WITH_YOUR_API_KEY";

  const modelsPath = join(piDir, "models.json");
  const authPath = join(piDir, "auth.json");

  writeFileSync(
    modelsPath,
    `${JSON.stringify(
      {
        providers: {
          [piProvider]: {
            ...(baseUrl ? { baseUrl } : {}),
            models: [{ id: opts.model, name: opts.model }],
          },
        },
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(
    authPath,
    `${JSON.stringify(
      {
        [piProvider]: { type: "api_key", key },
      },
      null,
      2,
    )}\n`,
  );
  chmodSync(authPath, 0o600);

  if (!isGateway) {
    console.error(
      `⚠ Set your ${opts.provider} API key in ${join(agentDir, ".pi-agent", "auth.json")} before running.`,
    );
  }

  return [modelsPath, authPath];
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function homedirEscape(): string {
  // Launcher script reads $HOME at runtime, not at generation time —
  // makes the launcher portable across users / hostnames.
  return "$HOME";
}
